unstable_features = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
wrap_comments = true
fn_single_line = true
force_multiline_blocks = true
merge_imports = true
overflow_delimited_expr = true
where_single_line = true